language: php

php:
  - 7.1
  
services:
  - mysql

before_script:
  - cp .env.travis .env
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('isY2metT') WHERE user='root';\nFLUSH PRIVILEGES;\nCREATE DATABASE conushop\n" | mysql -u root
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan database:sync

script:
  - vendor/bin/phpunit
  
notifications:
  email: false