-- MySQL Script generated by MySQL Workbench
-- Wed Sep 27 01:44:35 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema conushop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema conushop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `conushop` DEFAULT CHARACTER SET utf8 ;
USE `conushop` ;

-- -----------------------------------------------------
-- Table `conushop`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conushop`.`User` ;

CREATE TABLE IF NOT EXISTS `conushop`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(25) NULL,
  `admin` TINYINT NULL,
  `physicalAddress` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conushop`.`ElectronicType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conushop`.`ElectronicType` ;

CREATE TABLE IF NOT EXISTS `conushop`.`ElectronicType` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `dimensionUnit` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conushop`.`Electronic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conushop`.`Electronic` ;

CREATE TABLE IF NOT EXISTS `conushop`.`Electronic` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dimension` FLOAT NULL,
  `weight` FLOAT NULL,
  `modelNumber` VARCHAR(45) NULL,
  `brandName` VARCHAR(45) NULL,
  `hdSize` VARCHAR(25) NULL,
  `price` VARCHAR(45) NULL,
  `processorType` VARCHAR(45) NULL,
  `ramSize` VARCHAR(45) NULL,
  `cpuCores` INT NULL,
  `batteryInfo` VARCHAR(45) NULL,
  `os` VARCHAR(45) NULL,
  `camera` TINYINT NULL,
  `touchScreen` TINYINT NULL,
  `ElectronicType_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Electronic_ElectronicType_idx` (`ElectronicType_id` ASC),
  CONSTRAINT `fk_Electronic_ElectronicType`
    FOREIGN KEY (`ElectronicType_id`)
    REFERENCES `conushop`.`ElectronicType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- INSERT
-- -----------------------------------------------------
REPLACE INTO ElectronicType (id, name) values (1, "Desktop");
REPLACE INTO ElectronicType (id, name) values (2, "Laptop");
REPLACE INTO ElectronicType (id, name) values (3, "Monitor");
REPLACE INTO ElectronicType (id, name) values (4, "Tablet");
REPLACE INTO ElectronicType (id, name) values (5, "Television");

REPLACE INTO User (id, email, password, admin) values (1, 'admin@conushop.com', 'admin', 1);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
