version: '2'

services:
  mariadb:
    build: docker/mariadb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}


  laravel:
    build: .
    ports:
        - 80:80
    depends_on:
        - mariadb
    environment:
        - DB_HOST:mariadb
        - DB_DATABASE:${DB_DATABASE}
        - DB_USERNAME:${DB_USERNAME}
        - DB_PASSWORD:${DB_PASSWORD}
        - DB_CONNECTION:mysql
